## SUCESSOR E ANTECESSOR
## AUTOR: PROF. GUILHERME CARDOSO AGOSTINETTI

# ENTRADA DE DADOS
NUMERO = int(input("N1: "))


# PROCESSAMENTO 
ANT = NUMERO -1
SUC = NUMERO +1

# SAÍDA DE DADOS
print("O ANTECESSOR É:", ANT)
print("O SUCESSOR É:", SUC)